apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicorp-demo
  labels:
    app: hashicorp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashicorp-demo
  template:
    metadata:
      labels:
        app: hashicorp-demo
    spec:
      containers:
      - name: server
        image: abelgana/go_server_image:${TAG}
        ports:
        - containerPort: 80
        env:
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: database
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: host
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: password
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: username
---
apiVersion: v1
kind: Service
metadata:
  name: hashicorp-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hashicorp-demo
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hashicorp-demo
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: hashicorp-demo.${CLUSTER_SPECIFIC_DNS_ZONE}
    http:
      paths:
      - backend:
          serviceName: hashicorp-demo
          servicePort: 80
        path: /
