apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicorp-demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: server
        image: abelgana/go_server_image:007e9fd2f87148c3e9f49d09af221f5de2dc1b0d
        ports:
        - containerPort: 80
        env:
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: database
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: host
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: password
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: example-postgresql-all-in-one-secret
                key: username
